name: Run Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        # Add src directory to Python path
        echo "PYTHONPATH=$GITHUB_WORKSPACE/src:$PYTHONPATH" >> $GITHUB_ENV
        
    - name: Run tests
      run: |
        python scripts/run_tests.py
        
    - name: Test coverage report
      run: |
        echo "✅ All tests completed successfully!"
        echo "📊 Test coverage includes:"
        echo "  - Configuration validation"
        echo "  - Date calculations"
        echo "  - API response handling"
        echo "  - Email formatting"
        echo "  - PreK matching logic"
        echo "  - Error handling"
        echo "  - SMTP functionality"
